# Site Settings
title                    : "Gates Hotel Diagonal Barcelona"
title_separator          : "-"
name                     : "Gates Hotel Diagonal Barcelona"
description              : "Enjoy the spectacular design of the Gates Hotel Barcelona, a modern 4* design hotel near Torre Agbar. Book on our Official Website here for our Best Rate!"
url                      : "https://www.gateshotelbarcelona.com"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "TravelTripperWeb/gatesbercelona"

# Language Settings
default_lang             : 'en'
languages                : ['en', 'es']

# Reading Files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - media.json
  - models.json
  - node_modules
  - old_media.json
  - package.json
  - Rakefile
  - README
  - sitemap.json
  - tmp
keep_files:
  - .git
  - assets
rsync_copy:
- _assets
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: pretty
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

data_paginate: 
  per_page: 5
  data: 'blog'
  path: 'blog/page:num'
  pagination_template: 'blog/index.html'
  sort_field: 'date'
  sort_reverse: true

page_gen:
  - data: 'blog'
    template: 'blog-details'
    dir: 'blog'
  - data: 'partners'
    template: 'partner-details'
    dir: 'partners'

booking_widget_url: https://gateshotelbarcelona.reztrip.com/mobile