 # Site settings
title: Key West Hotels - The Gates Hotel Key West
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The Gates of Key West is a new upscale lifestyle hotel in Key West Florida, offering sophisticated accommodations and unforgettable experiences.
baseurl: "" # the subpath of your site, e.g. /blog 
url: "https://www.gateshotelkeywest.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

permalink: pretty
default_lang: 'en'
languages: ['en']

exclude: ['sitemap.json']

booking_widget_url: https://gateshotelkeywest.reztrip.com/mobile

page_gen:
  - data: 'partners'
    template: 'partner-details'
    dir: 'partners'
  - data: 'events'
    template: 'event-details'
    dir: 'events'

